spring:
  application:
    name: spring-mongodb-demo
  data:
    mongodb:
      uri: mongodb+srv://tayphuong1109:PhuongTay110903%40@javaphuongtay.qkqk0o3.mongodb.net/?retryWrites=true&w=majority&appName=JavaPhuongTay
      database: Task
